behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 100
    summary_freq: 10000
environment_parameters:
  ballSpeed:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.1
        value: 2.5
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.3
        value: 3.0
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.5
        value: 3.5
      - name: Lesson3
        value: 4.0
  boardRadius:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.1
        value: 8
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.3
        value: 7.5
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.5
        value: 7
      - name: Lesson3
        value: 6
  ballNums:
    curriculum:
      - name: Lesson0
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.1
        value: 5
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.3
        value: 6
      - name: Lesson2
        completion_criteria:
          measure: progress
          behavior: My Behavior
          signal_smoothing: true
          min_lesson_length: 0
          threshold: 0.5
        value: 7
      - name: Lesson3
        value: 8        