behaviors:
  My Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.4
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      rnd:
        gamma: 0.99
        strength: 0.5
        network_settings:
          hidden_units: 128
          num_layers: 3
        learning_rate: 0.0001
    keep_checkpoints: 5
    max_steps: 30000000
    time_horizon: 512
    summary_freq: 30000
